# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unix-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest]
            emacs-version:
                - 26.1
                - 26.2
                - 26.3
                - 27.1
                - 27.2
                - snapshot
                
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
            version: ${{ matrix.emacs-version }}
      - uses: conao3/setup-cask@master
      - name: Run test
        run:
            make unix-ci
